language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"

env:
  - DJANGO=django==1.5.12
  - DJANGO=django==1.6.11
  - DJANGO=django==1.7.7
  - DJANGO=django==1.8

install:
  - pip install -q $DJANGO
  - pip install -q flake8 coveralls coverage
  - python setup.py install

before_script:
  - make flake8

script:
  - make coverage

after_success:
  - make coveralls
